import { User, Post, Story, Notification, Conversation, Message, FriendRequest, Photo } from "./types";

export const currentUser: User = {
  id: "1",
  name: "Alex Johnson",
  username: "alexjohnson",
  email: "alex@example.com",
  avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Alex_Johnson_1968.jpg",
  coverPhoto: "/images/cover-photo-mountains-landscape.jpg",
  bio: "Living life one adventure at a time 🌍 | Software Engineer | Coffee enthusiast ☕",
  location: "San Francisco, CA",
  workplace: "TechCorp Inc.",
  education: "UC Berkeley",
  friendCount: 847,
  isOnline: true,
  joinedDate: "January 2019",
  relationship: "Single",
};

export const mockUsers: User[] = [
  {
    id: "2",
    name: "Sarah Mitchell",
    username: "sarahmitchell",
    email: "sarah@example.com",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/2/25/Minister_Mitchell_July_20_headshot_DSC6710a.jpg",
    coverPhoto: "/images/cover-photo-city-skyline.jpg",
    bio: "Designer & Creative Director | Making the world more beautiful ✨",
    location: "New York, NY",
    workplace: "Creative Studio",
    education: "NYU",
    friendCount: 1243,
    mutualFriends: 12,
    isOnline: true,
    joinedDate: "March 2018",
  },
  {
    id: "3",
    name: "Marcus Williams",
    username: "marcuswilliams",
    email: "marcus@example.com",
    avatar: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3122882.png&w=350&h=254",
    coverPhoto: "/images/cover-photo-beach-sunset.jpg",
    bio: "Entrepreneur | Investor | Fitness junkie 💪",
    location: "Los Angeles, CA",
    workplace: "Williams Ventures",
    education: "Stanford University",
    friendCount: 2156,
    mutualFriends: 8,
    isOnline: false,
    joinedDate: "June 2017",
  },
  {
    id: "4",
    name: "Emily Chen",
    username: "emilychen",
    email: "emily@example.com",
    avatar: "https://m.media-amazon.com/images/M/MV5BZThmMjZjYTMtNjkyMy00NmExLTgyY2YtOTQ3NGZiZGZlYzFmXkEyXkFqcGc@._V1_.jpg",
    coverPhoto: "/images/cover-photo-forest-path.jpg",
    bio: "Data Scientist | AI enthusiast | Book lover 📚",
    location: "Seattle, WA",
    workplace: "DataTech Labs",
    education: "MIT",
    friendCount: 634,
    mutualFriends: 23,
    isOnline: true,
    joinedDate: "September 2020",
  },
  {
    id: "5",
    name: "James Rodriguez",
    username: "jamesrodriguez",
    email: "james@example.com",
    avatar: "https://publish.realmadrid.com/content/dam/portals/realmadrid-com/es-es/sports/football/legendary-players/james-rodriguez/assets/1330783932802.jpg",
    coverPhoto: "/images/cover-photo-urban-street.jpg",
    bio: "Photographer | Traveler | Storyteller 📷",
    location: "Miami, FL",
    workplace: "Freelance",
    education: "Florida State University",
    friendCount: 3421,
    mutualFriends: 5,
    isOnline: false,
    joinedDate: "February 2016",
  },
  {
    id: "6",
    name: "Priya Patel",
    username: "priyapatel",
    email: "priya@example.com",
    avatar: "https://s.yimg.com/ny/api/res/1.2/hpSf1XHDmToH6R5HEHv2qg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTIwNDg7aD0xODU4O2NmPXdlYnA-/https://media.zenfs.com/en/where_is_the_buzz_814/37f4180215a0ca436f4b375464b2fa92",
    coverPhoto: "/images/cover-photo-colorful-market.jpg",
    bio: "Product Manager | UX advocate | Tea lover 🍵",
    location: "Austin, TX",
    workplace: "StartupHub",
    education: "UT Austin",
    friendCount: 892,
    mutualFriends: 17,
    isOnline: true,
    joinedDate: "April 2019",
  },
  {
    id: "7",
    name: "David Kim",
    username: "davidkim",
    email: "david@example.com",
    avatar: "https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DavidKim.jpg",
    coverPhoto: "/images/cover-photo-mountain-peak.jpg",
    bio: "Full-stack developer | Open source contributor | Gamer 🎮",
    location: "Chicago, IL",
    workplace: "DevCo",
    education: "University of Illinois",
    friendCount: 456,
    mutualFriends: 31,
    isOnline: true,
    joinedDate: "November 2021",
  },
];

export const mockPosts: Post[] = [
  {
    id: "p1",
    author: mockUsers[0],
    content: "Just got back from an amazing trip to Japan! 🇯🇵 The cherry blossoms were absolutely breathtaking. Tokyo is such a vibrant city — the food, the culture, the people. Already planning my next visit! Who else has been to Japan? Drop your recommendations below! 🌸",
    image: "https://www.gotokyo.org/en/story/guide/hanami-guide/images/main_670.webp",
    timestamp: "2 hours ago",
    likes: 247,
    liked: false,
    shares: 18,
    privacy: "public",
    comments: [
      {
        id: "c1",
        author: mockUsers[1],
        content: "Oh wow, I've always wanted to visit Japan! The cherry blossoms look stunning 😍",
        timestamp: "1 hour ago",
        likes: 12,
        liked: false,
      },
      {
        id: "c2",
        author: mockUsers[3],
        content: "Japan is incredible! Make sure to visit Kyoto next time — the temples are amazing 🏯",
        timestamp: "45 minutes ago",
        likes: 8,
        liked: false,
      },
    ],
  },
  {
    id: "p2",
    author: mockUsers[1],
    content: "Excited to share that I just launched my new design portfolio! 🎨 After months of hard work, it's finally live. Check it out and let me know what you think. Feedback is always welcome! Link in bio ✨",
    timestamp: "4 hours ago",
    likes: 189,
    liked: true,
    shares: 34,
    privacy: "public",
    comments: [
      {
        id: "c3",
        author: mockUsers[2],
        content: "Congratulations Sarah! Your work is always so inspiring 🙌",
        timestamp: "3 hours ago",
        likes: 5,
        liked: false,
      },
    ],
  },
  {
    id: "p3",
    author: mockUsers[2],
    content: "Morning workout done ✅ 5am club is no joke but the results speak for themselves. Remember: consistency beats perfection every single time. What's your morning routine? Let's motivate each other! 💪🔥",
    image: "https://hips.hearstapps.com/hmg-prod/images/mh-formcheck-6644d0094e70c.png?crop=0.5xw:1xh;center,top&resize=640:*",
    timestamp: "6 hours ago",
    likes: 412,
    liked: false,
    shares: 67,
    privacy: "public",
    comments: [
      {
        id: "c4",
        author: mockUsers[4],
        content: "This is so motivating! I need to get back to my morning routine 😅",
        timestamp: "5 hours ago",
        likes: 3,
        liked: false,
      },
      {
        id: "c5",
        author: currentUser,
        content: "Respect! I can barely wake up at 7am 😂",
        timestamp: "4 hours ago",
        likes: 7,
        liked: false,
      },
    ],
  },
  {
    id: "p4",
    author: mockUsers[3],
    content: "Captured this incredible sunset at the beach last evening 🌅 Sometimes you just need to stop, breathe, and appreciate the beauty around us. Nature never disappoints. #Photography #Sunset #BeachLife",
    image: "https://images.pexels.com/photos/6210284/pexels-photo-6210284.jpeg",
    timestamp: "Yesterday",
    likes: 876,
    liked: false,
    shares: 123,
    privacy: "public",
    comments: [],
  },
  {
    id: "p5",
    author: mockUsers[4],
    content: "Just finished reading 'Atomic Habits' by James Clear for the second time. Every re-read reveals something new. The concept of 1% improvements compounding over time is genuinely life-changing. Highly recommend to anyone looking to build better habits! 📚",
    timestamp: "2 days ago",
    likes: 134,
    liked: true,
    shares: 29,
    privacy: "friends",
    comments: [
      {
        id: "c6",
        author: mockUsers[5],
        content: "Such a great book! The habit stacking technique changed my life 🙏",
        timestamp: "2 days ago",
        likes: 11,
        liked: false,
      },
    ],
  },
  {
    id: "p6",
    author: currentUser,
    content: "Working on an exciting new project this week! Can't share too many details yet, but it involves some cutting-edge AI technology. Stay tuned for updates! 🚀 #Tech #AI #BuildingInPublic",
    timestamp: "3 days ago",
    likes: 203,
    liked: false,
    shares: 15,
    privacy: "public",
    comments: [
      {
        id: "c7",
        author: mockUsers[0],
        content: "Sounds exciting! Can't wait to hear more 👀",
        timestamp: "3 days ago",
        likes: 4,
        liked: false,
      },
    ],
  },
];

export const mockStories: Story[] = [
  {
    id: "s1",
    author: mockUsers[0],
    image: "https://i.ytimg.com/vi/6G2YXU8ElwM/mqdefault.jpg",
    timestamp: "2h",
    viewed: false,
  },
  {
    id: "s2",
    author: mockUsers[1],
    image: "https://i.ytimg.com/vi/-0Um0nEK8RE/maxresdefault.jpg",
    timestamp: "4h",
    viewed: false,
  },
  {
    id: "s3",
    author: mockUsers[2],
    image: "https://m.media-amazon.com/images/I/71DHSS4rZLL._AC_UF1000,1000_QL80_.jpg",
    timestamp: "5h",
    viewed: true,
  },
  {
    id: "s4",
    author: mockUsers[3],
    image: "https://i.ytimg.com/vi/X6HpPSvjUMM/maxresdefault.jpg",
    timestamp: "8h",
    viewed: false,
  },
  {
    id: "s5",
    author: mockUsers[4],
    image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1702071254i/75664963.jpg",
    timestamp: "12h",
    viewed: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "like",
    actor: mockUsers[0],
    postId: "p6",
    postPreview: "Working on an exciting new project...",
    timestamp: "2 minutes ago",
    read: false,
    message: "Sarah Mitchell liked your post",
  },
  {
    id: "n2",
    type: "comment",
    actor: mockUsers[1],
    postId: "p6",
    postPreview: "Working on an exciting new project...",
    timestamp: "15 minutes ago",
    read: false,
    message: "Marcus Williams commented on your post",
  },
  {
    id: "n3",
    type: "friend_request",
    actor: mockUsers[5],
    timestamp: "1 hour ago",
    read: false,
    message: "David Kim sent you a friend request",
  },
  {
    id: "n4",
    type: "like",
    actor: mockUsers[2],
    postId: "p6",
    postPreview: "Working on an exciting new project...",
    timestamp: "2 hours ago",
    read: true,
    message: "Emily Chen liked your post",
  },
  {
    id: "n5",
    type: "share",
    actor: mockUsers[3],
    postId: "p6",
    timestamp: "3 hours ago",
    read: true,
    message: "James Rodriguez shared your post",
  },
  {
    id: "n6",
    type: "birthday",
    actor: mockUsers[4],
    timestamp: "Today",
    read: false,
    message: "Today is Priya Patel's birthday! 🎂",
  },
  {
    id: "n7",
    type: "comment",
    actor: mockUsers[0],
    postId: "p3",
    timestamp: "Yesterday",
    read: true,
    message: "Sarah Mitchell replied to your comment",
  },
  {
    id: "n8",
    type: "friend_request",
    actor: mockUsers[2],
    timestamp: "2 days ago",
    read: true,
    message: "Emily Chen accepted your friend request",
  },
];

const mockMessages1: Message[] = [
  { id: "m1", senderId: "2", content: "Hey! How's it going?", timestamp: "10:30 AM", read: true, type: "text" },
  { id: "m2", senderId: "1", content: "Hey Sarah! I'm doing great, just got back from Japan 🇯🇵", timestamp: "10:32 AM", read: true, type: "text" },
  { id: "m3", senderId: "2", content: "Oh wow, that's amazing! I saw your post. The cherry blossoms looked gorgeous!", timestamp: "10:33 AM", read: true, type: "text" },
  { id: "m4", senderId: "1", content: "It was absolutely incredible. You should definitely go sometime!", timestamp: "10:35 AM", read: true, type: "text" },
  { id: "m5", senderId: "2", content: "I'm definitely adding it to my bucket list 😍 Are you free this weekend? A few of us are getting together for dinner", timestamp: "10:40 AM", read: true, type: "text" },
  { id: "m6", senderId: "1", content: "That sounds fun! Count me in 🙌", timestamp: "10:41 AM", read: false, type: "text" },
];

const mockMessages2: Message[] = [
  { id: "m7", senderId: "3", content: "Bro, did you see the game last night?!", timestamp: "Yesterday", read: true, type: "text" },
  { id: "m8", senderId: "1", content: "Yes!! That last-minute goal was insane 🔥", timestamp: "Yesterday", read: true, type: "text" },
  { id: "m9", senderId: "3", content: "We should watch the next one together. I'll host!", timestamp: "Yesterday", read: true, type: "text" },
  { id: "m10", senderId: "1", content: "Absolutely! Just let me know the date", timestamp: "Yesterday", read: true, type: "text" },
  { id: "m11", senderId: "3", content: "Will do 👊", timestamp: "Yesterday", read: true, type: "text" },
];

const mockMessages3: Message[] = [
  { id: "m12", senderId: "4", content: "Hi Alex! I wanted to ask about that AI project you mentioned", timestamp: "Monday", read: true, type: "text" },
  { id: "m13", senderId: "1", content: "Hey Emily! Sure, what would you like to know?", timestamp: "Monday", read: true, type: "text" },
  { id: "m14", senderId: "4", content: "Are you using any specific ML frameworks? I've been working with PyTorch lately", timestamp: "Monday", read: true, type: "text" },
  { id: "m15", senderId: "1", content: "Mostly TensorFlow for this one, but I've been curious about PyTorch. Maybe we can collaborate!", timestamp: "Monday", read: true, type: "text" },
  { id: "m16", senderId: "4", content: "That would be awesome! Let's set up a call this week 🚀", timestamp: "Monday", read: true, type: "text" },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv1",
    participants: [currentUser, mockUsers[0]],
    lastMessage: mockMessages1[mockMessages1.length - 1],
    unreadCount: 1,
    isOnline: true,
    messages: mockMessages1,
  },
  {
    id: "conv2",
    participants: [currentUser, mockUsers[1]],
    lastMessage: mockMessages2[mockMessages2.length - 1],
    unreadCount: 0,
    isOnline: false,
    messages: mockMessages2,
  },
  {
    id: "conv3",
    participants: [currentUser, mockUsers[2]],
    lastMessage: mockMessages3[mockMessages3.length - 1],
    unreadCount: 0,
    isOnline: true,
    messages: mockMessages3,
  },
  {
    id: "conv4",
    participants: [currentUser, mockUsers[3]],
    lastMessage: { id: "m17", senderId: "5", content: "Check out this photo I took! 📷", timestamp: "Tuesday", read: true, type: "text" },
    unreadCount: 3,
    isOnline: false,
    messages: [
      { id: "m17", senderId: "5", content: "Check out this photo I took! 📷", timestamp: "Tuesday", read: false, type: "text" },
    ],
  },
  {
    id: "conv5",
    participants: [currentUser, mockUsers[4]],
    lastMessage: { id: "m18", senderId: "1", content: "Thanks for the book recommendation!", timestamp: "Wednesday", read: true, type: "text" },
    unreadCount: 0,
    isOnline: true,
    messages: [
      { id: "m18", senderId: "1", content: "Thanks for the book recommendation!", timestamp: "Wednesday", read: true, type: "text" },
    ],
  },
];

export const mockFriendRequests: FriendRequest[] = [
  { id: "fr1", from: mockUsers[5], timestamp: "2 hours ago", mutualFriends: 14 },
  { id: "fr2", from: { ...mockUsers[4], id: "8", name: "Lena Park", username: "lenapark", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/23/Lena_Park%2C_2015_%28cropped%29.jpg", mutualFriends: 7 }, timestamp: "1 day ago", mutualFriends: 7 },
  { id: "fr3", from: { ...mockUsers[3], id: "9", name: "Omar Hassan", username: "omarhassan", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/23/Lena_Park%2C_2015_%28cropped%29.jpg", mutualFriends: 3 }, timestamp: "3 days ago", mutualFriends: 3 },
];

export const mockPhotos: Photo[] = [
  { id: "ph1", url: "/images/photo-gallery-japan-temple.jpg", caption: "Ancient temple in Kyoto 🏯", timestamp: "2 hours ago", likes: 89, comments: 12 },
  { id: "ph2", url: "/images/photo-gallery-cherry-blossoms.jpg", caption: "Cherry blossom season 🌸", timestamp: "2 hours ago", likes: 134, comments: 23 },
  { id: "ph3", url: "/images/photo-gallery-tokyo-night.jpg", caption: "Tokyo at night ✨", timestamp: "3 hours ago", likes: 201, comments: 34 },
  { id: "ph4", url: "/images/photo-gallery-mount-fuji.jpg", caption: "Mount Fuji view 🗻", timestamp: "1 day ago", likes: 312, comments: 45 },
  { id: "ph5", url: "/images/photo-gallery-sushi-food.jpg", caption: "Best sushi I've ever had! 🍣", timestamp: "1 day ago", likes: 178, comments: 28 },
  { id: "ph6", url: "/images/photo-gallery-shibuya-crossing.jpg", caption: "Shibuya crossing madness 🚶", timestamp: "2 days ago", likes: 267, comments: 41 },
  { id: "ph7", url: "/images/photo-gallery-bamboo-forest.jpg", caption: "Arashiyama bamboo grove 🎋", timestamp: "2 days ago", likes: 445, comments: 67 },
  { id: "ph8", url: "/images/photo-gallery-japanese-garden.jpg", caption: "Peaceful Japanese garden 🌿", timestamp: "3 days ago", likes: 156, comments: 19 },
  { id: "ph9", url: "/images/photo-gallery-street-food.jpg", caption: "Street food adventures 🍜", timestamp: "3 days ago", likes: 223, comments: 31 },
];

export const suggestedFriends: User[] = [
  { ...mockUsers[5], id: "10", name: "Nina Torres", username: "ninatorres", avatar: "https://i.ytimg.com/vi/TLiVoHHVZOA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLALzHKDK4PeOcgiork_kmGGC7qflg", mutualFriends: 9 },
  { ...mockUsers[4], id: "11", name: "Ryan Cooper", username: "ryancooper", avatar: "https://martensonlaw.com/wp-content/uploads/2025/10/Nina-Torres-no-background-1.jpg", mutualFriends: 6 },
  { ...mockUsers[3], id: "12", name: "Aisha Okafor", username: "aishaokafor", avatar: "https://m.media-amazon.com/images/M/MV5BOTFlNGIyZjUtOTE4OC00YzgwLTk3YzQtODBlZThhMzBiZDlmXkEyXkFqcGc@._V1_.jpg", mutualFriends: 15 },
  { ...mockUsers[2], id: "13", name: "Lucas Ferreira", username: "lucasferreira", avatar: "/images/avatar-lucas-ferreira.jpg", mutualFriends: 4 },
  { ...mockUsers[1], id: "14", name: "Mei Zhang", username: "meizhang", avatar: "/images/avatar-mei-zhang.jpg", mutualFriends: 11 },
  { ...mockUsers[0], id: "15", name: "Tom Bradley", username: "tombradley", avatar: "/images/avatar-tom-bradley.jpg", mutualFriends: 8 },
];
